services:
  - type: web
    name: childstory-backend
    runtime: java
    env: java
    rootDir: ChildStoryApp/ChildStoryApp
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/ChildStoryApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    healthCheckPath: /health
